include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    public_member_api_docs: ignore
    eol_at_end_of_file: ignore
    require_trailing_commas: ignore
    sort_constructors_first: ignore
